const CONSONANTS = [
  { id:'aleph', glyph:'א', answers:['알레프','aleph','alef'] },
  { id:'bet', glyph:'ב', answers:['베트','벳','bet','beth'] },
  { id:'gimel', glyph:'ג', answers:['기멜','김멜','gimel','gimmel'] },
  { id:'dalet', glyph:'ד', answers:['달레트','달렛','dalet','daleth'] },
  { id:'he', glyph:'ה', answers:['헤','헤이','he','hey'] },
  { id:'vav', glyph:'ו', answers:['바브','와우','바우','vav','waw'] },
  { id:'zayin', glyph:'ז', answers:['자인','zayin'] },
  { id:'het', glyph:'ח', answers:['헤트','헷','het','heth','chet'] },
  { id:'tet', glyph:'ט', answers:['테트','텟','tet','teth'] },
  { id:'yod', glyph:'י', answers:['요드','욧','yod','yodh'] },
  { id:'kaf', glyph:'כ', answers:['카프','kaf','kaph','khaf'] },
  { id:'lamed', glyph:'ל', answers:['라메드','라멧','lamed','lamedh'] },
  { id:'mem', glyph:'מ', answers:['멤','메므','mem'] },
  { id:'nun', glyph:'נ', answers:['눈','nun'] },
  { id:'samekh', glyph:'ס', answers:['싸메크','사메크','사멕','samekh','samech'] },
  { id:'ayin', glyph:'ע', answers:['아인','ayin'] },
  { id:'pe', glyph:'פ', answers:['페','페이','pe','peh','phe'] },
  { id:'tsade', glyph:'צ', answers:['차데','짜데','차디','tsade','tsadi','tzade'] },
  { id:'qof', glyph:'ק', answers:['코프','쿼프','qof','qoph','kof'] },
  { id:'resh', glyph:'ר', answers:['레쉬','레시','resh'] },
  { id:'shin', glyph:'שׁ', answers:['쉰','신','shin'] },
  { id:'sin', glyph:'שׂ', answers:['신','씬','sin'] },
  { id:'tav', glyph:'ת', answers:['타브','타우','tav','taw'] }
];

const VOWELS = [
  { id:'shewa', mark:'ְ', demo:'בְ', answers:['쉐와','슈와','셰와','쉐바','shewa','sheva'] },
  { id:'hatef-segol', mark:'ֱ', demo:'בֱ', answers:['하탑 쎄골','하테프 세골','하테프세골','hataf segol','hatef segol'] },
  { id:'hatef-patah', mark:'ֲ', demo:'בֲ', answers:['하탑 파탁','하테프 파타흐','하테프 파타ḥ','하테프 파타','하테프파타흐','hataf patah','hatef patah'] },
  { id:'hatef-qamats', mark:'ֳ', demo:'בֳ', answers:['하탑 카메츠','하테프 카메츠','하테프카메츠','하테프 카마츠','hataf qamats','hatef qamats','hataf qametz'] },
  { id:'hireq', mark:'ִ', demo:'בִ', answers:['히렉','히리크','hireq','hiriq'] },
  { id:'tsere', mark:'ֵ', demo:'בֵ', answers:['체레','쩨레','tsere','tsereh'] },
  { id:'segol', mark:'ֶ', demo:'בֶ', answers:['쎄골','세골','segol'] },
  { id:'patah', mark:'ַ', demo:'בַ', answers:['파타흐','파타','파탁','patah','pathah'] },
  { id:'qamats', mark:'ָ', demo:'בָ', answers:['카메츠','카마츠','qamats','qametz','kamatz'] },
  { id:'holam', mark:'ֹ', demo:'בֹ', answers:['홀람','호람','홀렘','holam','holem'] },
  { id:'qibbuts', mark:'ֻ', demo:'בֻ', answers:['키부츠','qibbuts','kubbutz','qibbus'] },
  { id:'hireq-yod', mark:'ִ', demo:'בִי', answers:['히렉 요드','히리크 요드','히릭 요드','hireq yod','hiriq yod','hireq-yod','hiriq-yod'] },
  { id:'tsere-yod', mark:'ֵ', demo:'בֵי', answers:['쩨레 요드','체레 요드','쯔레 요드','tsere yod','tsere-yod','tsere yodh','sere yod'] },
  { id:'shureq', mark:'ֵ', demo:'בוּ', answers:['슈렉','슈레크','수렉','shureq','shurek','shuruk','sureq'] },
  { id:'holem-vav', mark:'ֵ', demo:'בוֹ', answers:['홀렘 바브','홀람 바브','홀렘 와우','홀람 와우','holem vav','holam vav','holem waw','holam waw','holem-vav'] }
];
